### ISSUE TITLE
PHP demo not working in sub directory

### ISSUE THREAD

**Issue by JHGitty** [xing/xing-api-samples#2]
The PHP demo should be working in sub directories.
Change in the template file from ``href="/login"`` to ``href="login"``.

I have not further check it so please check it before uploading a fix.
Hope somebody will fix this :-)

**Comment by JanAhrens** [comment]
Thanks for reporting this issue. It's open since a long time. Sorry for that.

@dawez refactored the PHP example substantially. I think this issue is no longer valid. If there are still problems please open a new one.
